MPESA_CONSUMER_KEY: 'cABGtLC4JVhPnmC6JS45Xq3c1kG0leaevikPNIKMrDSAGC6K'
MPESA_CONSUMER_SECRET: '7w3q3BpOG2bnQR4gQxfh83irqQJnVooatM0DwSeqikSXhaNicCwcqnfsFDFk6HwN'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORT_CODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: 'MTc0Mzc5YmZiMjc5ZjlhYTliZGJjZjE1OGU5N2RkNzFhNDY3Y2QyZTBjODkzMDU5YjEwZjc4ZTZiNzJhZGExZWQyYzkxOTIwMjQwNDEzMjMwMzIz'
CALLBACK_URL: 'https://6c92-41-90-32-69.ngrok-free.app'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"